### ISSUE TITLE
Error with Plugin Launcher (solved with v1.3)

### ISSUE THREAD

**Issue by JQ3B94** [Lamer87/Space_Engineers_DLC_unlocker#49]
Game now refuses to launch when this is installed

**Comment by JQ3B94** [comment]
![image](https://github.com/Lamer87/Space_Engineers_DLC_unlocker/assets/52463691/9090cf63-eb57-431c-8b08-9a784365042f)

**Comment by Lamer87** [comment]
I'm downloading the game, please wait guys :)

**Comment by Lamer87** [comment]
update tested and uploaded. you can enjoy the game :)

**Comment by JQ3B94** [comment]
![image](https://github.com/Lamer87/Space_Engineers_DLC_unlocker/assets/52463691/d941e08d-6d2b-44b5-a7c6-5ad7fc8eefa4)
still throws up the error..

**Comment by Lamer87** [comment]
Mine works correctly...
-If you have the tool, use it and select "remove".
-Do a recheck of game files via steam.
-Try again.

**Comment by EagleGundam** [comment]
i get the same error but only wen using the plungin launcher

**Comment by YMGMengsk** [comment]
I also have this problem with the Plugin Launcher but also with the Normal start

**Comment by JQ3B94** [comment]
same for me , tried on a windows virtual machine and still no luck

**Comment by Candy6132** [comment]
Same issue on Plugin Loader. Works without the PL.

**Comment by Lamer87** [comment]
Never used the plugin loader guys.
5.2 is the latest version of the plugin loader (you can see here), if it creates error it's because it is not compatible (anymore) with the plugin launcher.
So, use creamapi OR plugin launcher for now, and let's wait for an updated creamapi.

Before the release I always test it on my legit game and I can use creamapi with no problem at all.

**Comment by Lamer87** [comment]
Reproduced the REAL error message:

![pluginlauncherror](https://github.com/Lamer87/Space_Engineers_DLC_unlocker/assets/65097384/03dc4a7f-73b2-4d5e-b37a-082df3cc1b33)

**Comment by Lamer87** [comment]
UPDATE:
seems that with creamapi v4.5.0.0 the launcher doesn't give error, but Idk if its ok to start the game with the old version, because there are fixes that include Space Engineers (in v5.1.0.0).

![pluginwith45](https://github.com/Lamer87/Space_Engineers_DLC_unlocker/assets/65097384/2131631f-b264-4246-8da8-eb8a5d6df483)


let me do some testing...

**Comment by Lamer87** [comment]
UPDATE 2:
tested, the game start, plugin menù is present, it works.

So, for now:
1- install creamapi via my tool
2- reach the folder "Backup\CreamAPI\old_v4.5.0.0" and copy the file "steam_api64.dll"
3- go back to "Bin64" folder and paste the file (overwriting)
4- you can use the plugin launcher.

**Comment by Lamer87** [comment]
v1.3 version is online.

Let me know if it's ok ;)

**Comment by JQ3B94** [comment]
> UPDATE 2: tested, the game start, plugin menù is present, it works.
> 
> So, for now: 1- install creamapi via my tool 2- reach the folder "Backup\CreamAPI\old_v4.5.0.0" and copy the file "steam_api64.dll" 3- go back to "Bin64" folder and paste the file (overwriting) 4- you can use the plugin launcher.
> 
> I'll update the tool to prevent this error.

this fix worked , but for future refferance I was using steam only
