### ISSUE TITLE
Deactivating already owned DLC. Bug after last minor patch.

### ISSUE THREAD

**Issue by I2pRandom** [Lamer87/Space_Engineers_DLC_unlocker#51]
Removing the lines for the owned DLC, just results in them being deactivated instead of leaving them be.

**Comment by CompellingGerble** [comment]
same here

**Comment by Lamer87** [comment]
Can you tell me please if you are using just the base game or Plugin Launcher?
I'm trying to reproduce this thing.

**Comment by Lamer87** [comment]
This is my base game + creamapi 5.2 (not using Plugin Launcher):

- Deluxe dlc: bought but disabled in steam (because it takes 3gb).
- Anniversary pack: not owned
- Signal pack: not owned
<br>

my cream_api.ini dlc section:
```
[dlc]
573160 = Space Engineers Deluxe
573161 = Space Engineers Artwork
573900 = Space Engineers 2013
2569770 = Space Engineers - Anniversary Pack
2914120 = Space Engineers - Signal Pack
```
<br>

ingame proof that dlc not owned are enabled:
<details><summary>click here to show</summary><p>

![ingame](https://github.com/Lamer87/Space_Engineers_DLC_unlocker/assets/65097384/83084e7a-9ad1-4967-b111-f3734263d247)

</p></details>

**Comment by Lamer87** [comment]
Ok guys, looks like Keen decided to make everyone's life easier :)
is no longer needed to delete purchased DLCs from the list.
Before it was necessary, otherwise you would get the same effect as of this thread, and dlcs could not be used ingame.

Thanks for reporting, I'll correct the guide!
